version: "3.9"

services:
  prod:
    image: theraudmickael/cv-vue3-prod:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"

  dev:
    image: cv-vue3-dev:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./:/app"
    command: "sh -c 'npm install && npm run serve'"
    ports:
      - "3001:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
