FROM node:16.13-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx
COPY ./configs/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html